import { useState } from 'react';
import { Folder, FileText, ChevronRight, ChevronDown, X, Copy, Check } from 'lucide-react';
import { repoTree, RepoItem } from '@/data/specData';
import useIntersectionObserver from '@/hooks/useIntersectionObserver';

interface TreeNodeProps {
  item: RepoItem;
  level: number;
  onFileClick: (item: RepoItem) => void;
}

const TreeNode = ({ item, level, onFileClick }: TreeNodeProps) => {
  const [isOpen, setIsOpen] = useState(level < 2);

  if (item.type === 'file') {
    return (
      <button
        onClick={() => onFileClick(item)}
        className="w-full flex items-center gap-2 py-1.5 px-2 rounded-md hover:bg-secondary/50 transition-colors text-left group"
        style={{ paddingLeft: `${level * 12 + 8}px` }}
      >
        <FileText className="w-4 h-4 text-primary flex-shrink-0" />
        <span className="text-xs md:text-sm text-muted-foreground group-hover:text-foreground truncate flex-1">
          {item.name}
        </span>
        {item.generatedBy && (
          <span className="text-[10px] px-1.5 py-0.5 rounded bg-primary/10 text-primary flex-shrink-0">
            {item.generatedBy}
          </span>
        )}
      </button>
    );
  }

  return (
    <div>
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="w-full flex items-center gap-2 py-1.5 px-2 rounded-md hover:bg-secondary/50 transition-colors text-left"
        style={{ paddingLeft: `${level * 12 + 8}px` }}
      >
        {isOpen ? (
          <ChevronDown className="w-4 h-4 text-muted-foreground flex-shrink-0" />
        ) : (
          <ChevronRight className="w-4 h-4 text-muted-foreground flex-shrink-0" />
        )}
        <Folder className={`w-4 h-4 flex-shrink-0 ${isOpen ? 'text-primary' : 'text-muted-foreground'}`} />
        <span className="text-xs md:text-sm text-foreground font-medium truncate">{item.name}</span>
        {item.generatedBy && (
          <span className="text-[10px] px-1.5 py-0.5 rounded bg-primary/10 text-primary ml-auto flex-shrink-0">
            {item.generatedBy}
          </span>
        )}
      </button>
      {isOpen && item.children && (
        <div>
          {item.children.map((child, i) => (
            <TreeNode 
              key={`${child.name}-${i}`} 
              item={child} 
              level={level + 1} 
              onFileClick={onFileClick}
            />
          ))}
        </div>
      )}
    </div>
  );
};

const RepoMap = () => {
  const [selectedFile, setSelectedFile] = useState<RepoItem | null>(null);
  const [copied, setCopied] = useState(false);
  const { ref, isIntersecting } = useIntersectionObserver();

  const handleCopy = async () => {
    if (selectedFile?.preview) {
      await navigator.clipboard.writeText(selectedFile.preview);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleCopyPath = async (path: string) => {
    await navigator.clipboard.writeText(path);
  };

  return (
    <section id="repo-map" className="py-16 md:py-24 px-4">
      <div className="max-w-4xl mx-auto">
        {/* Section Header */}
        <div 
          ref={ref}
          className={`text-center mb-8 md:mb-12 transition-all duration-700 ${
            isIntersecting ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'
          }`}
        >
          <span className="chip chip-primary mb-4">Repository</span>
          <h2 className="text-2xl sm:text-3xl md:text-4xl font-bold text-foreground mb-4">
            Generated Repository Structure
          </h2>
          <p className="text-muted-foreground max-w-xl mx-auto text-sm md:text-base">
            The complete file structure generated by the agent pipeline. Click any file to preview its contents.
          </p>
        </div>

        <div className="flex gap-4 md:gap-6 flex-col lg:flex-row">
          {/* File Tree */}
          <div className="flex-1 rounded-2xl bg-card border border-border overflow-hidden">
            <div className="px-4 py-3 border-b border-border bg-secondary/30 flex items-center justify-between">
              <span className="text-xs md:text-sm font-semibold text-foreground">📁 project-root</span>
              <span className="text-[10px] text-muted-foreground">Click to explore</span>
            </div>
            <div className="p-2 max-h-[400px] md:max-h-[500px] overflow-y-auto">
              {repoTree.map((item, i) => (
                <TreeNode 
                  key={`${item.name}-${i}`} 
                  item={item} 
                  level={0} 
                  onFileClick={setSelectedFile}
                />
              ))}
            </div>
          </div>

          {/* Preview Panel */}
          <div className="flex-1 rounded-2xl bg-card border border-border overflow-hidden">
            <div className="px-4 py-3 border-b border-border bg-secondary/30 flex items-center justify-between gap-2">
              <div className="flex items-center gap-2 min-w-0">
                <span className="text-xs md:text-sm font-semibold text-foreground truncate">
                  {selectedFile ? selectedFile.name : 'File Preview'}
                </span>
                {selectedFile?.generatedBy && (
                  <span className="text-[10px] px-1.5 py-0.5 rounded bg-primary/10 text-primary flex-shrink-0">
                    {selectedFile.generatedBy}
                  </span>
                )}
              </div>
              <div className="flex items-center gap-2 flex-shrink-0">
                {selectedFile?.preview && (
                  <button 
                    onClick={handleCopy}
                    className="p-1 rounded hover:bg-secondary transition-colors text-muted-foreground hover:text-foreground"
                    title="Copy content"
                  >
                    {copied ? <Check className="w-4 h-4 text-success" /> : <Copy className="w-4 h-4" />}
                  </button>
                )}
                {selectedFile && (
                  <button 
                    onClick={() => setSelectedFile(null)}
                    className="p-1 rounded hover:bg-secondary transition-colors"
                  >
                    <X className="w-4 h-4 text-muted-foreground" />
                  </button>
                )}
              </div>
            </div>
            <div className="p-4 max-h-[340px] md:max-h-[440px] overflow-y-auto">
              {selectedFile && selectedFile.preview ? (
                <pre className="text-[10px] md:text-xs font-mono text-muted-foreground whitespace-pre-wrap leading-relaxed">
                  {selectedFile.preview}
                </pre>
              ) : (
                <div className="flex items-center justify-center h-40 text-muted-foreground text-sm">
                  Select a file to preview
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default RepoMap;
