
-- Startup ideas table
CREATE TABLE public.startup_ideas (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  status text NOT NULL DEFAULT 'intake',
  current_phase text NOT NULL DEFAULT 'intake',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.startup_ideas ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read ideas" ON public.startup_ideas FOR SELECT TO public USING (true);
CREATE POLICY "Anyone can insert ideas" ON public.startup_ideas FOR INSERT TO public WITH CHECK (true);
CREATE POLICY "Anyone can update ideas" ON public.startup_ideas FOR UPDATE TO public USING (true);
CREATE POLICY "Anyone can delete ideas" ON public.startup_ideas FOR DELETE TO public USING (true);

-- Idea messages (chat with agents)
CREATE TABLE public.idea_messages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  idea_id uuid REFERENCES public.startup_ideas(id) ON DELETE CASCADE NOT NULL,
  agent text NOT NULL DEFAULT 'chief_of_staff',
  role text NOT NULL DEFAULT 'user',
  content text NOT NULL,
  phase text NOT NULL DEFAULT 'intake',
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.idea_messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read messages" ON public.idea_messages FOR SELECT TO public USING (true);
CREATE POLICY "Anyone can insert messages" ON public.idea_messages FOR INSERT TO public WITH CHECK (true);

-- Idea documents (generated by agents at each phase)
CREATE TABLE public.idea_documents (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  idea_id uuid REFERENCES public.startup_ideas(id) ON DELETE CASCADE NOT NULL,
  agent text NOT NULL,
  phase text NOT NULL,
  title text NOT NULL,
  content text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'pending',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.idea_documents ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read docs" ON public.idea_documents FOR SELECT TO public USING (true);
CREATE POLICY "Anyone can insert docs" ON public.idea_documents FOR INSERT TO public WITH CHECK (true);
CREATE POLICY "Anyone can update docs" ON public.idea_documents FOR UPDATE TO public USING (true);
CREATE POLICY "Anyone can delete docs" ON public.idea_documents FOR DELETE TO public USING (true);

-- Enable realtime for messages
ALTER PUBLICATION supabase_realtime ADD TABLE public.idea_messages;
ALTER PUBLICATION supabase_realtime ADD TABLE public.idea_documents;
